### ISSUE TITLE
Question: how to use it locally?

### ISSUE THREAD

**Issue by set-soft** [easyw/vrm360#1]
This is very nice!
I tried: 
- https://easyw.github.io/vrm360/index.html
- https://easyw.github.io/vrm360/icezum-obj.html

Without problems, but if I try it using the files from git (in my machine) it doesn't work. How can I make it work locally? I.e.:

```shell
$ git clone https://github.com/easyw/vrm360.git
$ cd vrm360
$ x-www-browser index.html
```

**Comment by Pablo2048** [comment]
Hi,
if you take a look into developer console, you can see that it's CORS problem - ( see https://threejs.org/docs/index.html#manual/en/introduction/How-to-run-things-locally ) . Try to run it from local server (`php -S localhost:8000' and then point your browser to http://localhost:8000 )...

**Comment by set-soft** [comment]
Thanks @Pablo2048 !  I used the Python alternative: 

```shell
$ python3 -m http.server
```

And worked perfectly

**Comment by Pablo2048** [comment]
You are welcome :-) I'm proud user of KiBot, so I'm pretty curious when Kibot support exporting VRML model for vrm360 :D ...
